CC     := g++
CFLAGS := $(CFLAGS) -Wall -O3 -march=native

all : ffbench

ffbench : main.cpp mirrorbuf.c fixedSizeMemoryLF.c
	$(CC) $(CFLAGS) main.cpp mirrorbuf.c fixedSizeMemoryLF.cpp -lpthread -latomic -o ffbench

clean :
	rm -f ffbench mirrorbuf.o fixedSizeMemoryLF.o
